language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t qassimov/docker-react -f Dockerfile.dev .

scripts:
  - docker run -e CI=true qassimov/docker-react npm run test